  name: Minimal OIDC Release

  on:
    push:
      tags:
        - "[0-9]+\\.[0-9]+\\.[0-9]+"
        - "[0-9]+\\.[0-9]+\\.[0-9]+.post[0-9]+"
        - "[0-9]+\\.[0-9]+\\.[0-9]+[a-z]+[0-9]+"
        - "[0-9]+\\.[0-9]+\\.[0-9]+rc[0-9]+"

  jobs:
    build:
      name: Build the source tarball and the wheel
      runs-on: ubuntu-latest
      environment: release
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: Install dependencies
          run: pip install build

        - name: Create packages
          run: python -m build

        - name: Verify build output
          run: ls -l dist/ || exit 1

        - name: Archive packages
          uses: actions/upload-artifact@v4
          with:
            name: python-dist
            path: dist

    publish:
      name: Publish build artifacts
      needs: build
      runs-on: ubuntu-latest
      environment: release
      permissions:
        id-token: write
      steps:
        - name: Retrieve packages
          uses: actions/download-artifact@v4
          with:
            name: python-dist
            path: dist

        - name: Verify downloaded packages
          run: ls -l dist/ || exit 1

        - name: Publish to PyPI (OIDC)
          if: "! contains(github.ref_name, 'rc')"
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: "https://upload.pypi.org/legacy/"
            verbose: true

        - name: Publish to Test PyPI (OIDC)
          if: contains(github.ref_name, 'rc')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: "https://test.pypi.org/legacy/"
            verbose: true

    create_release:
      name: Create a GitHub Release
      needs: publish
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Create Release
          uses: actions/create-release@v1.1.4
          with:
            tag_name: ${{ github.ref_name }}
            release_name: "Release ${{ github.ref_name }}"
            body: "Release notes go here."
            draft: false
            prerelease: ${{ contains(github.ref_name, 'rc') }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
